In [96]:
import networkx as nx
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sys
sys.path.append("..") 
import stockcorr as sc 
from networkx.algorithms import community
import sklearn.cluster as cluster


In [8]:
## Makes so that there is no output


## Read in data
stock_df = pd.read_csv('../../data/stock_market_data/stockdf.csv')


## Convert date to datetime
stock_df['Date'] = pd.to_datetime(stock_df['Date'])


## find first date of every year in the stockdf

first_date = stock_df['Date'].dt.year.drop_duplicates()

## split the stockdf into dataframes, one for each year

dataframes_ = [stock_df[stock_df['Date'].dt.year == year] for year in first_date]
dataframes_ = [df.set_index('Date') for df in dataframes_]
corr_list = []
for i in dataframes_:
    curr_ = sc.get_corr_matrix(i, 0.9)
    ## make every value to 1 if above 0
    curr_ = np.where(curr_ > 0, 1, 0)
    corr_list.append(curr_)

## sum all correlation matrices in corr_list

total_sum = sum(corr_list)




calculating corr matrix
A has 884701 nan values
calculating corr matrix
A has 856541 nan values
calculating corr matrix
A has 829984 nan values
calculating corr matrix
A has 778072 nan values
calculating corr matrix
A has 709273 nan values
calculating corr matrix
A has 557527 nan values
calculating corr matrix
A has 512382 nan values
calculating corr matrix
A has 397991 nan values
calculating corr matrix
A has 285840 nan values
calculating corr matrix
A has 184634 nan values
calculating corr matrix
A has 120634 nan values
calculating corr matrix
A has 107794 nan values
calculating corr matrix
A has 121689 nan values
calculating corr matrix
A has 94235 nan values
calculating corr matrix
A has 124344 nan values
calculating corr matrix
A has 110027 nan values
calculating corr matrix
A has 64869 nan values
calculating corr matrix
A has 85581 nan values


In [9]:
## create graph from total_sum with weighted edges
G = nx.from_numpy_matrix(total_sum)


# communities = community.greedy_modularity_communities(G)
#     #position by community
# colorlist = [ 'r', 'g', 'b', 'c', 'm', 'y', 'brown', 'orange', 'purple' ]

# setLst = list(communities)
# plt.figure(figsize = (50,30))
# for index, sg in enumerate(setLst):
#     #draw with orange color text
#     print(index)
#     pos = nx.spring_layout(G.subgraph(sg))
#     nx.draw(G.subgraph(sg), pos= pos, node_color= colorlist[index % 7], with_labels=True)
# plt.show()


# G.remove_nodes_from(list(nx.isolates(G)))
# pos = nx.spring_layout(G)
# colorlist = [ 'r', 'g', 'b', 'c', 'm', 'y', 'brown', 'orange', 'purple' ]
# wcc = nx.connected_components( G )
# setLst = list(wcc) 
# len(setLst)
# plt.figure(figsize = (50,30))
# for index, sg in enumerate(setLst):
#     #draw with orange color text
#     nx.draw(G.subgraph(sg), pos= pos, node_color= colorlist[index % 7], with_labels=True, font_size=20)
# plt.show()

In [12]:
corr_, total_sum,X = cw.split_into_years()
corr_

calculating corr matrix
A has 884701 nan values
calculating corr matrix
A has 856541 nan values
calculating corr matrix
A has 829984 nan values
calculating corr matrix
A has 778072 nan values
calculating corr matrix
A has 709273 nan values
calculating corr matrix
A has 557527 nan values
calculating corr matrix
A has 512382 nan values
calculating corr matrix
A has 397991 nan values
calculating corr matrix
A has 285840 nan values
calculating corr matrix
A has 184634 nan values
calculating corr matrix
A has 120634 nan values
calculating corr matrix
A has 107794 nan values
calculating corr matrix
A has 121689 nan values
calculating corr matrix
A has 94235 nan values
calculating corr matrix
A has 124344 nan values
calculating corr matrix
A has 110027 nan values
calculating corr matrix
A has 64869 nan values
calculating corr matrix
A has 85581 nan values


[array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]),
 array([[0, 1, 0, ..., 1, 0, 0],
        [1, 0, 0, ..., 1, 1, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [1, 1, 0, ..., 0, 0, 0],
        [0, 1, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]),
 array([[0, 1, 0, ..., 1, 0, 0],
        [1, 0, 0, ..., 1, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [1, 1, 0, ..., 0, 0, 0],
   

In [17]:
stockdf = pd.read_csv('./../data/stock_market_data/stockdf.csv')

corr_df = sc.get_corr_matrix(stockdf)

corr_df = np.where(np.isfinite(corr_df), corr_df, 0)


calculating corr matrix
A has 2294 nan values


In [93]:
## make corr_df into a graph
G = nx.from_numpy_matrix(corr_df)

A = nx.to_scipy_sparse_array(G)


clustering = AP(max_iter=1000,).fit(A)

In [88]:
cols = stockdf.columns

In [89]:
center_tickers = cols[clustering.cluster_centers_indices_]

center_stocks = stockdf[center_tickers]

center_stocks.corr()

A     AAALY     AACAY       AAL       AAP      AAPL      ABBV  \
A      1.000000 -0.105557 -0.021987  0.043375  0.810568  0.971801  0.873068   
AAALY -0.105557  1.000000  0.362700  0.505361  0.200395 -0.142618  0.095376   
AACAY -0.021987  0.362700  1.000000  0.720165  0.003007 -0.154051 -0.043930   
AAL    0.043375  0.505361  0.720165  1.000000  0.292381 -0.065198 -0.337592   
AAP    0.810568  0.200395  0.003007  0.292381  1.000000  0.785842  0.612438   
...         ...       ...       ...       ...       ...       ...       ...   
ZIJMF  0.718718 -0.135978 -0.249423 -0.438901  0.340684  0.759415  0.826793   
ZION   0.240159  0.240015  0.326716  0.493124 -0.009083  0.181397  0.837432   
ZNH    0.397924  0.606435  0.599124  0.309124  0.513849  0.329144  0.245976   
ZSHGY  0.954236 -0.385421 -0.372455 -0.787139  0.580973  0.931327  0.803669   
ZTS    0.969354 -0.083528 -0.271268 -0.599613  0.667364  0.957844  0.854626   

            ABC      ABLT       ABT  ...     YFGSF     YMDAF       YUM  \
A      0.841602 -0.406890  0.973970  ... -0.694921 -0.608124  0.929698   
AAALY  0.194738  0.177498 -0.125879  ...  0.132431 -0.279571  0.071596   
AACAY  0.102224  0.345907 -0.066377  ...  0.468060 -0.403840  0.064353   
AAL    0.301022  0.476508  0.021340  ...  0.481565 -0.272723  0.120842   
AAP    0.945784 -0.283091  0.824837  ... -0.623222 -0.839851  0.891827   
...         ...       ...       ...  ...       ...       ...       ...   
ZIJMF  0.406138 -0.534376  0.647010  ... -0.706605  0.040619  0.516492   
ZION   0.023963 -0.081635  0.189086  ... -0.544707  0.219105  0.069217   
ZNH    0.563856  0.270676  0.395255  ...  0.287925 -0.454365  0.540201   
ZSHGY  0.636032 -0.503001  0.955679  ... -0.622805 -0.106658  0.875541   
ZTS    0.732654 -0.537510  0.986900  ... -0.640395 -0.282753  0.947045   

          YWGRF       ZBH     ZIJMF      ZION       ZNH     ZSHGY       ZTS  
A     -0.726230  0.810433  0.718718  0.240159  0.397924  0.954236  0.969354  
AAALY  0.257683  0.045107 -0.135978  0.240015  0.606435 -0.385421 -0.083528  
AACAY  0.057247  0.332830 -0.249423  0.326716  0.599124 -0.372455 -0.271268  
AAL    0.549547  0.428513 -0.438901  0.493124  0.309124 -0.787139 -0.599613  
AAP   -0.131515  0.843481  0.340684 -0.009083  0.513849  0.580973  0.667364  
...         ...       ...       ...       ...       ...       ...       ...  
ZIJMF -0.548588  0.275005  1.000000  0.496441  0.020439  0.890154  0.876429  
ZION  -0.730061  0.264246  0.496441  1.000000 -0.067060  0.684437  0.745157  
ZNH   -0.004801  0.513618  0.020439 -0.067060  1.000000 -0.135529  0.053955  
ZSHGY -0.748409  0.639995  0.890154  0.684437 -0.135529  1.000000  0.953274  
ZTS   -0.762678  0.715366  0.876429  0.745157  0.053955  0.953274  1.000000  

[1079 rows x 1079 columns]

In [92]:
# heatmap of the center stocks
import seaborn as sns
import matplotlib.pyplot as plt

center_stock_corr = center_stocks.corr()

avg_corr = center_stock_corr.mean()
avg_base = np.mean(corr_df, axis=0)
np.min(avg_corr)

KeyboardInterrupt: 

In [80]:
# Find index of clusters
clustering.cluster_centers_indices_

array([  41,   49,   74,   96,  150,  198,  254,  291,  303,  379,  381,
        391,  408,  418,  419,  515,  529,  540,  556,  569,  636,  644,
        651,  705,  726,  768,  771,  773,  785,  796,  805,  812,  822,
        830,  865,  879,  885,  901,  905,  957,  958, 1006, 1007, 1062,
       1077])

In [111]:
## Find all the clusters of clsutering
print(clustering.cluster_centers_indices_)

print(clustering.cluster_centers_)

## Find labels of each node in each cluster
clustering.labels_

[  41   49   74   96  150  198  254  291  303  379  381  391  408  418
  419  515  529  540  556  569  636  644  651  705  726  768  771  773
  785  796  805  812  822  830  865  879  885  901  905  957  958 1006
 1007 1062 1077]
  (0, 0)	0.42315308327695295
  (0, 1)	0.16039100743703322
  (0, 2)	0.06869440469900749
  (0, 3)	0.11782821402393784
  (0, 4)	0.42786780404419045
  (0, 5)	0.4329768783639659
  (0, 6)	0.5098622777721928
  (0, 7)	0.4773366275176938
  (0, 8)	-0.15680054343213337
  (0, 9)	0.3450588351475687
  (0, 10)	-0.06879201612366048
  (0, 11)	0.08062240006565526
  (0, 12)	-0.07585577757468073
  (0, 13)	-0.25834416666386767
  (0, 14)	-0.06340622811447923
  (0, 15)	0.34695963723876655
  (0, 16)	0.0843197699929318
  (0, 17)	0.44305964551384663
  (0, 18)	0.4277114693040124
  (0, 19)	0.16733442874844076
  (0, 20)	0.16823452073628603
  (0, 21)	0.4033677316334046
  (0, 22)	0.5885433037809316
  (0, 23)	0.4101013498734359
  (0, 24)	0.2772985809708233
  :	:
  (44, 1054)	-0.6301983939819

array([30, 13, 16, ..., 44, 44,  2])

In [135]:
from sklearn import covariance

G = nx.from_numpy_matrix(corr_df)

## give the nodes a label
G = nx.relabel_nodes(G, dict(zip(range(len(G.nodes())), stockdf.columns)))


A = nx.to_scipy_sparse_array(G)


clusters = cluster.AffinityPropagation().fit(A)

  (0, 1)	-0.1055568517470077
  (0, 2)	-0.021987012590072096
  (0, 3)	0.043375227128948535
  (0, 4)	0.8105684290517843
  (0, 5)	0.9718007916591248
  (0, 6)	0.8730682416250697
  (0, 7)	0.8416022864137294
  (0, 8)	-0.40689039023127804
  (0, 9)	0.9739695174754384
  (0, 10)	-0.6305182042650764
  (0, 11)	-0.2966126499259049
  (0, 12)	0.3529369315868824
  (0, 13)	-0.7267364424011576
  (0, 14)	-0.519341326122139
  (0, 15)	0.8909386328154509
  (0, 16)	-0.3165363703552476
  (0, 17)	0.9839661453162645
  (0, 18)	0.8540630783224051
  (0, 19)	0.8645898367559203
  (0, 20)	-0.41480359272358364
  (0, 21)	0.9832860851194777
  (0, 22)	0.8144487889912442
  (0, 23)	0.9572939642649395
  (0, 24)	0.9662033603721873
  (0, 25)	0.455039588477491
  :	:
  (1079, 1054)	-0.2878450003361882
  (1079, 1055)	0.6738911463321553
  (1079, 1056)	0.8844951656694332
  (1079, 1057)	0.41017146544833805
  (1079, 1058)	-0.28605014534204415
  (1079, 1059)	-0.15458896670807973
  (1079, 1060)	0.28083621123606656
  (1079, 1061)	0.855

In [129]:
n_labels = clusters.labels_.max()

print(stockdf.columns)
symbols= np.array(stockdf.columns).T
for i in range(n_labels + 1):
    print(f"Cluster {i + 1}: {', '.join(symbols[clusters.labels_ == i])}")



Index(['A', 'AAALY', 'AACAY', 'AAL', 'AAP', 'AAPL', 'ABBV', 'ABC', 'ABLT',
       'ABT',
       ...
       'YMDAF', 'YUM', 'YWGRF', 'ZBH', 'ZIJMF', 'ZION', 'ZNH', 'ZSHGY', 'ZTS',
       'ZURVY'],
      dtype='object', length=1080)
Cluster 1: AEHR, AIAGF, AMKBY, ARCC, BAESY, BCMXY, CLPXY, CMWAY, COP, CSIQ, DCNSF, GME, GTWCF, JNPR, JRONY, KBDCY, MAHMF, MSLOF, ORMP, PBA, PINC, SBKFF, SCPJ, SJR, SVTRF, TCLCF, THC, TONPF, TX
Cluster 2: ACFL, AGNC, AKBTY, ALR, CMHHF, CPCAY, CPYYF, CS, EDRWY, HNLGF, NLY, RIG, RMGOF, SINGY, SMEBF, SWRBY, TEF
Cluster 3: AAPL, ACN, ADP, AIZ, AJG, AMGN, AON, AZN, AZO, BRK-A, CHD, CHRW, CHT, CINF, CME, CNI, COST, CP, DE, DLMAF, ES, EW, EXR, FAST, HRL, HUM, JBHT, JNJ, KFRC, KLAC, LLY, LNT, LYV, MAA, MCD, MDLZ, MMC, MOH, MSFT, MSI, MTRAF, NEE, ORLY, PAYX, PEG, PEP, PG, PLD, RJF, RS, RSG, SO, SZLMY, TMO, TRI, TSCO, UNH, UNP, WCN, WEC, WM, WTKWY, XEL, ZURVY
Cluster 4: AHII, ATONF, AUTR, BPCGF, CGKEY, CIMDF, COL, CSSI, CSWYY, CYH, EFGXY, GARPF, HCMLY, HNTIF, HPIL, JAPA

In [117]:
print(symbols[clusters.cluster_centers_indices_])

['AIAGF' 'AKBTY' 'AON' 'AUTR' 'BMRN' 'CCGY' 'CNHI' 'DAHSF' 'DISH' 'FIS'
 'FITB' 'FOXA' 'GECFF' 'GLHD' 'GLPEF' 'ISUZY' 'JEXYF' 'JWN' 'KLMR' 'KWHIY'
 'MON' 'MRVGF' 'MTPOF' 'ODMUF' 'PAG' 'PWCDF' 'QBEIF' 'QUBSF' 'RE' 'RIOCF'
 'ROK' 'RXMD' 'SBGSF' 'SCGLY' 'SKFOF' 'SMTOY' 'SNV' 'STGPF' 'STT' 'TNABF'
 'TOELY' 'USB' 'USCS' 'XL' 'ZSHGY']
