In [14]:
import networkx as nx
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sys
sys.path.append("..") 
import stockcorr as sc 
from networkx.algorithms import community
from sklearn.cluster import  AffinityPropagation as AP


In [8]:
## Makes so that there is no output


## Read in data
stock_df = pd.read_csv('../../data/stock_market_data/stockdf.csv')


## Convert date to datetime
stock_df['Date'] = pd.to_datetime(stock_df['Date'])


## find first date of every year in the stockdf

first_date = stock_df['Date'].dt.year.drop_duplicates()

## split the stockdf into dataframes, one for each year

dataframes_ = [stock_df[stock_df['Date'].dt.year == year] for year in first_date]
dataframes_ = [df.set_index('Date') for df in dataframes_]
corr_list = []
for i in dataframes_:
    curr_ = sc.get_corr_matrix(i, 0.9)
    ## make every value to 1 if above 0
    curr_ = np.where(curr_ > 0, 1, 0)
    corr_list.append(curr_)

## sum all correlation matrices in corr_list

total_sum = sum(corr_list)




calculating corr matrix
A has 884701 nan values
calculating corr matrix
A has 856541 nan values
calculating corr matrix
A has 829984 nan values
calculating corr matrix
A has 778072 nan values
calculating corr matrix
A has 709273 nan values
calculating corr matrix
A has 557527 nan values
calculating corr matrix
A has 512382 nan values
calculating corr matrix
A has 397991 nan values
calculating corr matrix
A has 285840 nan values
calculating corr matrix
A has 184634 nan values
calculating corr matrix
A has 120634 nan values
calculating corr matrix
A has 107794 nan values
calculating corr matrix
A has 121689 nan values
calculating corr matrix
A has 94235 nan values
calculating corr matrix
A has 124344 nan values
calculating corr matrix
A has 110027 nan values
calculating corr matrix
A has 64869 nan values
calculating corr matrix
A has 85581 nan values


In [9]:
## create graph from total_sum with weighted edges
G = nx.from_numpy_matrix(total_sum)


# communities = community.greedy_modularity_communities(G)
#     #position by community
# colorlist = [ 'r', 'g', 'b', 'c', 'm', 'y', 'brown', 'orange', 'purple' ]

# setLst = list(communities)
# plt.figure(figsize = (50,30))
# for index, sg in enumerate(setLst):
#     #draw with orange color text
#     print(index)
#     pos = nx.spring_layout(G.subgraph(sg))
#     nx.draw(G.subgraph(sg), pos= pos, node_color= colorlist[index % 7], with_labels=True)
# plt.show()


# G.remove_nodes_from(list(nx.isolates(G)))
# pos = nx.spring_layout(G)
# colorlist = [ 'r', 'g', 'b', 'c', 'm', 'y', 'brown', 'orange', 'purple' ]
# wcc = nx.connected_components( G )
# setLst = list(wcc) 
# len(setLst)
# plt.figure(figsize = (50,30))
# for index, sg in enumerate(setLst):
#     #draw with orange color text
#     nx.draw(G.subgraph(sg), pos= pos, node_color= colorlist[index % 7], with_labels=True, font_size=20)
# plt.show()

In [12]:
corr_, total_sum,X = cw.split_into_years()
corr_

calculating corr matrix
A has 884701 nan values
calculating corr matrix
A has 856541 nan values
calculating corr matrix
A has 829984 nan values
calculating corr matrix
A has 778072 nan values
calculating corr matrix
A has 709273 nan values
calculating corr matrix
A has 557527 nan values
calculating corr matrix
A has 512382 nan values
calculating corr matrix
A has 397991 nan values
calculating corr matrix
A has 285840 nan values
calculating corr matrix
A has 184634 nan values
calculating corr matrix
A has 120634 nan values
calculating corr matrix
A has 107794 nan values
calculating corr matrix
A has 121689 nan values
calculating corr matrix
A has 94235 nan values
calculating corr matrix
A has 124344 nan values
calculating corr matrix
A has 110027 nan values
calculating corr matrix
A has 64869 nan values
calculating corr matrix
A has 85581 nan values


[array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]),
 array([[0, 1, 0, ..., 1, 0, 0],
        [1, 0, 0, ..., 1, 1, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [1, 1, 0, ..., 0, 0, 0],
        [0, 1, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]),
 array([[0, 1, 0, ..., 1, 0, 0],
        [1, 0, 0, ..., 1, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [1, 1, 0, ..., 0, 0, 0],
   

In [17]:
stockdf = pd.read_csv('./../data/stock_market_data/stockdf.csv')

corr_df = sc.get_corr_matrix(stockdf)

corr_df = np.where(np.isfinite(corr_df), corr_df, 0)


calculating corr matrix
A has 2294 nan values


In [18]:
## make corr_df into a graph
G = nx.from_numpy_matrix(corr_df)

A = nx.to_scipy_sparse_matrix(G)


clustering = AP().fit(A)



In [29]:
# Find index of clusters
clustering.cluster_centers_indices_


array([  41,   49,   74,   96,  150,  198,  254,  291,  303,  379,  381,
        391,  408,  418,  419,  515,  529,  540,  556,  569,  636,  644,
        651,  705,  726,  768,  771,  773,  785,  796,  805,  812,  822,
        830,  865,  879,  885,  901,  905,  957,  958, 1006, 1007, 1062,
       1077])

In [36]:
## Find all the clusters of clsutering
print(clustering.cluster_centers_)

## Find labels of each node in each cluster
clustering.labels_

[[ 0.42315308  0.16039101  0.0686944  ...  0.36292592  0.28362043
   0.34920582]
 [-0.77348003 -0.13568486 -0.07638719 ... -0.83384341 -0.86362423
  -0.62460159]
 [ 0.96967486  0.0291786   0.00831239 ...  0.90068563  0.9683254
   0.89020769]
 ...
 [-0.39773543 -0.09401366 -0.3894658  ...  0.58789066  0.44269389
  -0.34050307]
 [-0.39080415 -0.49610732  0.67950147 ... -0.21324045 -0.41197823
  -0.44122471]
 [ 0.95423646 -0.38542117 -0.3724553  ...  0.          0.95327434
   0.85324536]]


array([30, 13, 16, ..., 44, 44,  2])